CREATE TABLE EMPLOYEE (
    Fname VARCHAR2(15),
    Minit CHAR,
    Lname VARCHAR2(15),
    SSN NUMBER(10) NOT NULL,
    Bdate DATE,
    Address VARCHAR2(50),
    Sex CHAR,
    Salary NUMBER(10),
    Super_ssn NUMBER(10),
    Dno NUMBER(3),
    PRIMARY KEY(SSN)
);

CREATE TABLE DEPARTMENT (
    DNAME VARCHAR2(15),
    Dnumber NUMBER(3) NOT NULL,
    Mgr_ssn NUMBER(10),
    Mgr_start_date DATE,
    PRIMARY KEY (Dnumber),
    FOREIGN KEY(Mgr_ssn) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE DEPT_LOCATION (
    Dnumber NUMBER(3) NOT NULL,
    Dlocation VARCHAR2(25) NOT NULL,
    PRIMARY KEY(Dnumber, Dlocation),
    FOREIGN KEY(Dnumber) REFERENCES DEPARTMENT(Dnumber)
);

CREATE TABLE PROJECT (
    PNAME VARCHAR2(15),
    Pnumber NUMBER(3) NOT NULL,
    Plocation VARCHAR(30),
    Dnum NUMBER(3),
    PRIMARY KEY (Pnumber),
    FOREIGN KEY(Dnum) REFERENCES DEPARTMENT(Dnumber)
);

CREATE TABLE WORKS_ON (
    ESSN NUMBER(10) NOT NULL,
    Pno NUMBER(3) NOT NULL,
    Hour NUMBER(10, 1),
    PRIMARY KEY(ESSN, Pno),
    FOREIGN KEY(ESSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY(Pno) REFERENCES PROJECT(Pnumber)
);

CREATE TABLE DEPENDENT (
    Essn NUMBER(10) NOT NULL,
    Dependent_name VARCHAR2(30) NOT NULL,
    Sex CHAR,
    Bdate DATE,
    Relationship VARCHAR2(20),
    PRIMARY KEY(Essn, Dependent_name),
    FOREIGN KEY(Essn) REFERENCES EMPLOYEE(SSN)
);
