CREATE TABLE FARMER (
SSN NUMBER(3) NOT NULL,
NAME VARCHAR2(15),
AGE NUMBER(3),
REGIONID NUMBER(3),
PRIMARY KEY(SSN));

CREATE TABLE REGION (
REGIONID NUMBER(3) NOT NULL,
REGNAME VARCHAR2(15) NOT NULL,
CROPBUDGET NUMBER(10,2),
MANAGERID NUMBER(3),
PRIMARY KEY (REGIONID),
FOREIGN KEY(MANAGERID) REFERENCES FARMER(SSN));

CREATE TABLE GROWSCROPS (
SSN NUMBER(3) NOT NULL,
REGIONID NUMBER(3) NOT NULL,
CROP VARCHAR2 (15) NOT NULL,
REVENUE NUMBER(10, 2),
PRIMARY KEY(SSN, REGIONID, CROP),
FOREIGN KEY(SSN) REFERENCES FARMER(SSN),
FOREIGN KEY(REGIONID) REFERENCES REGION(REGIONID));

CREATE TABLE RCONTACT (
REGIONID NUMBER(3) NOT NULL,
FULLNAME VARCHAR2(25),
RPHONE VARCHAR2(15),
PRIMARY KEY(REGIONID),
FOREIGN KEY(REGIONID) REFERENCES REGION(REGIONID));
